Partysize:
 Normal: 5
 Premium: 10
 PremiumPlus: 50
Language: 'en'
Lang:
 en:
  Prefix: '&7[&6Party&7]'
  Error_Invitation: 'You can''t invite yourself.'
  Not_Online: 'The player &6%player% &7is not online.'
  Usage_Party_Invite: 'Use &6/Party invite [Player] &7to invite a player.'
  Usage_Party_Kick: 'Use &6/Party kick [Player] &7to kick a player.'
  Menu_Invite: '/Party &6invite [Player] &7- Invites a player'
  Menu_Accept: '/Party &6accept &7- Accepts a request'
  Menu_Leave: '/Party &6leave &7- Leaves the party'
  Menu_Kick: '/Party &6kick [Player] &7- Kicks a player'
  Menu_List: '/Party &6list &7- Shows all partymembers'
  Menu_Chat: '/Party &6chat &7- Sends a partymessage'
  Party_Changed_Server: 'The party joined the server &6%server%&7.'
  Already_In_Party: 'You are already in a party.'
  Not_In_Party: 'You are not in a party.'
  Party_Left: 'You left the party.'
  Player_Left_Party: '&6%player% &7left the party.'
  Player_Deleted_Party: '&6%player% &7closed the party.'
  Party_Created: 'Party successfully created.'
  Party_Deleted: 'You closed the party.'
  Leader: 'Leader'
  Member: 'Member'
  Party_Chat: '&6%player%&7: &a%message%'
  Party_Already_Full: 'The party is already full.'
  Player_Already_In_Party: '&6%player% &7is already in a party.'
  Player_Already_Has_Party: '&6%player% &7leads already a party.'
  Invitation: 'You invited &6%player%&7.'
  Invitation_Request: '&6%player% &7invited &7you &7to &7join &7his &7party. &7Use [command=/Party accept]&6/&6Party &6accept[/command] &7to &7join.'
  Player_Joined_Party: '&6%player% &7joined the party.'
  Joined_Party: 'You joined &6%player%''s &7party.'
  No_Invitation: 'You got no request.'
  Not_Party_Owner: 'You are no partyleader.'
  Kicked: 'You were kicked out of &6%player%''s &7party.'
  Player_Kicked: '&6%player% &7were kicked out of the party.'
  Player_Not_In_Party: '&6%player% &7is not in the party.'
  Add_Message: 'Please enter a message.'
 de:
  Prefix: '&7[&6Party&7]'
  Error_Invitation: 'Du kannst dich nicht selbst einladen.'
  Not_Online: 'Der Spieler &6%player% &7ist nicht online.'
  Usage_Party_Invite: 'Benutze &6/Party einladen [Spieler] &7um einen Spieler in deine Party einzuladen.'
  Usage_Party_Kick: 'Benutze &6/Party kick [Spieler] &7um einen Spieler aus deiner Party zu werfen.'
  Menu_Invite: '/Party &6einladen [Spieler] &7- L&aumldt ein Spieler ein'
  Menu_Accept: '/Party &6annehmen &7- Nimmt eine Anfrage an'
  Menu_Leave: '/Party &6verlassen &7- Verl&aumlsst die Party'
  Menu_Kick: '/Party &6kick [Spieler] &7- Wirft einen Spieler aus der Party'
  Menu_List: '/Party &6Liste &7- Zeigt die Mitglieder an'
  Menu_Chat: '/Party &6Chat &7- Sendet eine Partynachricht'
  Party_Changed_Server: 'Die Party betritt den Server &6%server%&7.'
  Already_In_Party: 'Du bist bereits in einer Party.'
  Not_In_Party: 'Du bist in keiner Party.'
  Party_Left: 'Du hast die Party verlassen.'
  Player_Left_Party: '&6%player% &7hat die Party verlassen.'
  Player_Deleted_Party: '&6%player% &7hat die Party aufgel&oumlst.'
  Party_Created: 'Die Party wurde erfolgreich erstellt.'
  Party_Deleted: 'Du hast die Party aufgel&oumlst.'
  Leader: 'Leiter'
  Member: 'Mitglieder'
  Party_Chat: '&6%player%&7: &a%message%'
  Party_Already_Full: 'Die Party ist bereits voll.'
  Player_Already_In_Party: '&6%player% &7ist bereits in einer Party.'
  Player_Already_Has_Party: '&6%player% &7hat bereits eine Party.'
  Invitation: 'Du hast &6%player% &7eingeladen.'
  Invitation_Request: '&6%player% &7hat &7dich &7in &7die &7Party &7eingeladen.[newline]&7Benutze [command=/Party annehmen]&6/&6Party &6annehmen[/command] &7um &7der &7Party &7beizutreten.'
  Player_Joined_Party: '&6%player% &7ist der Party beigetreten.'
  Joined_Party: 'Du bist der Party von &6%player% &7beigetreten.'
  No_Invitation: 'Du hast keine Einladung.'
  Not_Party_Owner: 'Du bist kein Partyleiter.'
  Kicked: 'Du wurdest aus &6%player%''s &7Party geworfen.'
  Player_Kicked: '&6%player% &7wurde aus der Party geworfen.'
  Player_Not_In_Party: '&6%player% &7ist nicht in der Party.'
  Add_Message: 'Bitte gebe eine Nachricht ein.'
 swe:
  Prefix: '&7[&6Party&7]'
  Error_Invitation: 'Du kan inte bjuda in dig sj&aumllv.'
  Not_Online: 'Spelaren &6%player% &7&aumlr inte online.'
  Usage_Party_Invite: 'Anv&aumlnd &6/Party invite [Player] &7f&oumlr att bjuda in en spelare.'
  Usage_Party_Kick: 'Anv&aumlnd &6/Party kick [Player] &7f&oumlr att avl&aumlgsna en spelare fr&aaumln ditt party.'
  Menu_Invite: '/Party &6invite [Player] &7- Bjud in en spelare.'
  Menu_Accept: '/Party &6accept &7- Acceptera en inbjudan.'
  Menu_Leave: '/Party &6leave &7- L&aumlmnar partyt.'
  Menu_Kick: '/Party &6kick [Player] &7- Avl&aumlgsna en spelare fr&aaumln ditt party.'
  Menu_List: '/Party &6list &7- Visar alla spelare i ditt party.'
  Menu_Chat: '/Party &6chat &7- Skicka ett meddelande i ditt party.'
  Party_Changed_Server: 'Ditt party har teleporterats till servern: &6%server%&7.'
  Already_In_Party: 'Du &aumlr redan i ett party!'
  Not_In_Party: 'Du &aumlr inte i ett party!'
  Party_Left: 'Du har l&aumlmnat partyt!'
  Player_Left_Party: '&6%player% &7har l&aumlmnat partyt.'
  Player_Deleted_Party: '&6%player% &7tog bart partyt.'
  Party_Created: 'Party skapades.'
  Party_Deleted: 'Du tog bort partyt'
  Leader: '&Aumlgare'
  Member: 'Medlem'
  Party_Chat: '&6%player%&7: &a%message%'
  Party_Already_Full: 'Partyt &aumlr fullt!'
  Player_Already_In_Party: '&6%player% &7&aumlr redan i ett party!'
  Player_Already_Has_Party: '&6%player% &7leder redan ett party!'
  Invitation: 'Du har bjudit in: &6%player%&7.'
  Invitation_Request: '&6%player% &7bj&oumld &7in &7dig &7till &7hans &7party. &7Anv&aumlnd [command=/Party accept]&6/&6Party &6accept[/command] &7f&oumlr &7att &7g&auml &7med!'
  Player_Joined_Party: '&6%player% &7har g&aaumltt med.'
  Joined_Party: 'Du gick med i &6%player%''s &7party.'
  No_Invitation: 'Du har ingen inbjudan.'
  Not_Party_Owner: 'Du &aumlr inte party ledaren!'
  Kicked: 'Du blev avl&aumlgsnad ur &6%player%''s &7party.'
  Player_Kicked: '&6%player% &7blev avl&aumlgsnad fr&aaumln party.'
  Player_Not_In_Party: '&6%player% &7&aumlr inte i ett party.'
  Add_Message: 'Skriv ett meddelande.'
 es:
  Prefix: '&7[&6Party&7]'
  Error_Invitation: 'No puedes invitarte a ti mismo.'
  Not_Online: 'El jugador &6%player% &7no se encuentra online.'
  Usage_Party_Invite: 'Usa &6/Party invite [jugador] &7para invitar a un jugador a tu fiesta.'
  Usage_Party_Kick: 'Usa &6/Party kick [Jugador] &7para kickear a alguien de tu fiesta.'
  Menu_Invite: '/Party &6invite [Jugador] &7- Invita a un jugador'
  Menu_Accept: '/Party &6accept &7- Accepta la invitacion de la fiesta'
  Menu_Leave: '/Party &6leave &7- Salir de la fiesta'
  Menu_Kick: '/Party &6kick [Jugador] &7- Kickear a un jugador de la fiesta'
  Menu_List: '/Party &6list &7- Muestra todos los miembros en la fiesta'
  Menu_Chat: '/Party &6chat &7- Envia un mensaje a todos los miembros de tu fiesta'
  Party_Changed_Server: 'La fiesta se ha unido al servidor &6%server%&7.'
  Already_In_Party: '&cYa estas en una fiesta. Usa &6/party leave &cpara salir de la fiesta'
  Not_In_Party: 'No estas en una fiesta.'
  Party_Left: '&cHas salido de la fiesta.'
  Player_Left_Party: '&6%player% &7salio de la fiesta.'
  Player_Deleted_Party: '&6%player% &7cerro la fiesta.'
  Party_Created: '&aLa fiesta ha sido exitosamente creada.'
  Party_Deleted: 'Has cerrado la fiesta.'
  Leader: 'Lider'
  Member: 'Miembro'
  Party_Chat: '&6%player%&7: &a%message%'
  Party_Already_Full: 'La fiesta esta llena.'
  Player_Already_In_Party: '&6%player% &7ya esta en la fiesta.'
  Player_Already_Has_Party: '&6%player% &7ya esta en una fiesta.'
  Invitation: 'Has invitado a &6%player%&7.'
  Invitation_Request: '&6%player% &7te invita a que te unas a su fiesta. &7Usa el comando [command=/Party accept]&6/&6Party &6accept[/command] &7para &7unirte a su fiesta.'
  Player_Joined_Party: '&6%player% &7se unio a la fiesta.'
  Joined_Party: '&aHas entrado a la fiesta de &6%player%.'
  No_Invitation: 'No tienes ninguna invitacion.'
  Not_Party_Owner: '&4No eres el lider de la fiesta.'
  Kicked: '&cHas sido expulsado fuera de la fiesta por &6%player%'
  Player_Kicked: '&6%player% &7fue expulsado de la fuesta.'
  Player_Not_In_Party: '&6%player% &7no esta en la fiesta.'
  Add_Message: 'Porfavor escribe un mensaje.'